# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GHACTIONS: ACTIVE

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, '3.10']

    steps:
    - uses: actions/checkout@v3
    # work around libxml install error using pip see
    # (360k views 2022-11)
    # https://stackoverflow.com/a/5178444/1497139
    # using How to apt-get install in a GitHub Actions workflow?
    # (70 k views 2022-11)
    # https://stackoverflow.com/a/58002908/1497139
    - name: Install lxml preqrequisites
      run: |
        sudo apt-get install libxml2-dev libxslt-dev python-dev
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        scripts/install
    - name: Run tests
      run: |
        scripts/test
